CREATE TABLE LEILAO (
    NUMEROLEILAO INT PRIMARY KEY,
    LOTEPRODUTOS INT,
    INSTFIN VARCHAR(255),
    DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ENDERECO VARCHAR(255)
);

-- Exemplo de inserção de dados
INSERT INTO LEILAO(NUMEROLEILAO, LOTEPRODUTOS, INSTFIN, ENDERECO) VALUES (1234, 1, '2123243124-0001', 'Rua Exemplo, 123');
